import { Check, Clock3, LoaderCircle } from 'lucide-react';
import type { BookingTable, TimeSlot } from '../../data/bookingMockData';
import EmptyState from '../common/EmptyState';

export default function TimeSlotSelector({ table, date, duration, players, slots, selected, checkingSlotId, message, onSelect, onChooseShorterDuration }: { table: BookingTable; date: string; duration: string; players: number; slots: TimeSlot[]; selected?: TimeSlot; checkingSlotId?: string | number; message?: string; onSelect: (slot: TimeSlot) => void; onChooseShorterDuration: () => void }) {
  const readable = new Date(`${date}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});
  return <section id="time-slots" className="scroll-mt-28 border border-[#D4AF37]/20 bg-[#100b0a]/95 p-5 sm:p-8">
    <p className="text-[9px] uppercase tracking-[.3em] text-[#D4AF37] mb-2">Step Three</p><h2 className="text-3xl sm:text-4xl text-[#F3E5AB] mb-5">Available Time Slots</h2>
    <div className="flex flex-wrap gap-x-6 gap-y-2 border-y border-white/10 py-4 mb-7 text-[10px] uppercase tracking-wider text-gray-400"><span><b className="text-gray-200 font-medium">{table.name}</b></span><span>{readable}</span><span>{duration}</span><span>{players} {players === 1 ? 'player' : 'players'}</span></div>
    {message && <p role="status" className="mb-5 border border-[#D4AF37]/20 bg-[#D4AF37]/5 px-4 py-3 text-xs text-[#F3E5AB]">{message}</p>}
    {!slots.length ? <EmptyState icon={Clock3} title="No Time Slots Available" description="This duration does not fit within today’s remaining opening hours. Choose a shorter session to see more times." actionLabel="Choose 30 Minutes" onAction={onChooseShorterDuration} compact/> : <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-3">{slots.map(slot => { const isSelected = selected?.id === slot.id; const checking = checkingSlotId === slot.id; const disabled = slot.status !== 'available' || checking; return <button key={slot.id} type="button" disabled={disabled} aria-pressed={isSelected} aria-busy={checking} onClick={() => onSelect(slot)} className={`min-h-[82px] border px-2 py-3 focus:outline-none focus:ring-2 focus:ring-[#D4AF37] transition-colors ${isSelected ? 'bg-[#D4AF37] border-[#D4AF37] text-[#080605]' : slot.status === 'available' ? 'border-[#D4AF37]/35 text-[#F3E5AB] hover:bg-[#D4AF37] hover:text-[#080605]' : slot.status === 'booked' ? 'border-red-900/40 bg-[#351414]/50 text-red-300/60 cursor-not-allowed' : 'border-gray-700 bg-gray-900/60 text-gray-600 cursor-not-allowed'}`}><span className="flex items-center justify-center gap-1 font-serif text-base">{checking ? <LoaderCircle size={14} className="animate-spin"/> : isSelected && <Check size={14}/>} {slot.start}</span><span className="block text-[8px] uppercase tracking-wider mt-1 opacity-70">{checking ? 'Checking...' : disabled ? (slot.status === 'booked' ? 'Booked' : 'Unavailable') : `to ${slot.end}`}</span></button>; })}</div>}
  </section>;
}
